

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
      

